language: rust
cache: cargo
matrix:
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
    env: RUN_CLIPPY=true
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - cargo install rustfmt || true
  - if [ "$RUN_CLIPPY" = "true" ] ; then cargo install clippy ; fi || true
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - if [ "$RUN_CLIPPY" = "true" ] ; then cargo clippy ; fi
  - cargo test --verbose
